---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: GLANCE
  become: true
  roles:
    - GLANCE

- hosts: KEYSTONE
  become: true
  roles:
    - KEYSTONE

- hosts: NOVA
  become: true
  roles:
    - NOVA




