- name: Installing Nova and pre-requisite
  apt:
    name:
      - nova-compute
      - python3-openstackclient
    state: present
    update_cache: yes

- name: Start The program
  service:
     name: nova-compute
     state: restarted
     enabled: yes
